apiVersion: v1
kind: Service
metadata:
  name: servicio-eks-tone-analysis-md
  labels:
    name: eks-tone-analysis-mdp-app
    app: eks-tone-analysis-mdp-app
spec:
  type: NodePort
  selector:
    app: eks-tone-analysis-mdp-app
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30027